#!/bin/sh

# Grab active game window id
winid=$(xwininfo -tree -root | grep "Minecraft" | tail -1 | awk '{ print $1 }')

# Check if window id does not exist (i.e. Minecraft is not currently running)
if [ -z "$winid" ] || [ "$winid" = "Binary" ]; then
	echo 'No Minecraft instance opened.'
	exit
fi

# Run repeated right-clicking action
xdotool mousedown --window "$winid" 3
